version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout
      
      # - restore_cache:
          # key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      # - run: mvn dependency:go-offline
      
      # - save_cache:
      #     paths:
      #       - ~/.m2
      #     key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      # - run: mvn package
      
      - run: 
          name: Get Github pull request
          command: |
            echo '${CI_PULL_REQUEST}'
            echo ${CI_PULL_REQUEST}
            PR_NUMBER=`echo '${CI_PULL_REQUEST}' | sed -e 's/.*\///g'`
            echo 'export ${PR_NUMBER}' >> $BASH_ENV
            echo '${PR_NUMBER}'

      # - run: mvn sonar:sonar -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.organization=${ORGANIZATION} -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONARQUBE_LOGIN}      
      
      # - store_test_results:
      #     path: target/surefire-reports
      
      # - store_artifacts:
          # path: target/demo-java-spring-0.0.1-SNAPSHOT.jar